In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('heart.csv')

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df.shape

(303, 14)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['target']), df['target'], test_size=0.2, random_state=42)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(X_train.head())
print(y_train.head())

(242, 13)
(61, 13)
(242,)
(61,)
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3  
132    1
202    0
196    0
75     1
176    0
Name: target, dtype: int64


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [8]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [9]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [10]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8852459016393442
Accuracy of Decision Trees 0.8360655737704918


In [12]:
confusion_matrix(y_test,y_pred1)

array([[25,  4],
       [ 3, 29]])

In [13]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  25   4
1   3  29

In [14]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  26   3
1   7  25

In [15]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [16]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
92              1                               1                         1
146             1                               1                         1
101             1                               0                         1
269             0                               0                         0
193             0                               0                         0
73              1                               1                         1
184             0                               0                         0
251             0                               0                         0
116             1                               1                         0
219             0                               0                         0

In [19]:
print("For Logistic regression Model")
print("-"*40)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*40)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
----------------------------------------
    0   1
0  25   4
1   3  29
----------------------------------------
Precision -  0.8787878787878788
Recall -  0.90625
F1 score -  0.8923076923076924


In [20]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  26   3
1   7  25
--------------------------------------------------
Precision -  0.8928571428571429
Recall -  0.78125
F1 score -  0.8333333333333334


In [21]:
precision_score(y_test,y_pred1,average=None)

array([0.89285714, 0.87878788])

In [22]:
precision_score(y_test,y_pred2,average=None)

array([0.78787879, 0.89285714])

In [23]:
recall_score(y_test,y_pred1,average=None)

array([0.86206897, 0.90625   ])