In [514]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [515]:
df =pd.read_csv('50_Startups.csv')
np.random.seed(5)
df=df.sample(5)
df

R&D Spend  Administration  Marketing Spend       State     Profit
42   23640.93        96189.63        148001.11  California   71498.49
29   65605.48       153032.06        107138.38    New York  101004.64
6   134615.46       147198.87        127716.82  California  156122.51
19   86419.70       153514.11             0.00    New York  122776.86
28   66051.52       182645.56        118148.20     Florida  103282.38

In [516]:

df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend       State
42   23640.93        96189.63        148001.11  California
29   65605.48       153032.06        107138.38    New York
6   134615.46       147198.87        127716.82  California
19   86419.70       153514.11             0.00    New York
28   66051.52       182645.56        118148.20     Florida

In [517]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [518]:
df.head()

R&D Spend  Administration  Marketing Spend       State
42   23640.93        96189.63        148001.11  California
29        NaN       153032.06        107138.38    New York
6   134615.46       147198.87        127716.82  California
19   86419.70             NaN             0.00    New York
28   66051.52       182645.56        118148.20         NaN

In [519]:
# Step 1 - Impute all missing values with mean of respective col
df0 =pd.DataFrame()

df0['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration']=df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend']=df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [520]:

# 0th Iteration
df0

R&D Spend  Administration  Marketing Spend
42   23640.9300        96189.63        148001.11
29   77681.9025       153032.06        107138.38
6   134615.4600       147198.87        127716.82
19   86419.7000       144766.53             0.00
28   66051.5200       182645.56        118148.20

In [521]:
# Remove the col1 imputed value
df1 =df0.copy()
df1.iloc[1,0]=np.nan
df1

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29        NaN       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       144766.53             0.00
28   66051.52       182645.56        118148.20

In [522]:
# Use first 3 rows to build a model and use the last for prediction
x =df1.iloc[[0,2,3,4],1:3]
x

Administration  Marketing Spend
42        96189.63        148001.11
6        147198.87        127716.82
19       144766.53             0.00
28       182645.56        118148.20

In [523]:
y = df1.iloc[[0,2,3,4],0]
y

42     23640.93
6     134615.46
19     86419.70
28     66051.52
Name: R&D Spend, dtype: float64

In [524]:
lr =LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([82875.61542753])

In [525]:
df1.iloc[1,0]=82875.61

In [526]:
df1

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29   82875.61       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       144766.53             0.00
28   66051.52       182645.56        118148.20

In [527]:
# Remove the col2 imputed value
df1.iloc[3,1]=np.nan
df1

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29   82875.61       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70             NaN             0.00
28   66051.52       182645.56        118148.20

In [528]:

# Use last 3 rows to build a model and use the first for prediction
x =df1.iloc[[0,1,2,4],[0,2]]
x

R&D Spend  Marketing Spend
42   23640.93        148001.11
29   82875.61        107138.38
6   134615.46        127716.82
28   66051.52        118148.20

In [529]:
y= df1.iloc[[0,1,2,4],1]
y   

42     96189.63
29    153032.06
6     147198.87
28    182645.56
Name: Administration, dtype: float64

In [530]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([340708.94516708])

In [531]:
df1.iloc[3,1]= 340708.94

In [532]:
df1

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29   82875.61       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       340708.94             0.00
28   66051.52       182645.56        118148.20

In [533]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan
df1

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29   82875.61       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       340708.94             0.00
28   66051.52       182645.56              NaN

In [534]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

R&D Spend  Administration
42   23640.93        96189.63
29   82875.61       153032.06
6   134615.46       147198.87
19   86419.70       340708.94

In [535]:

y = df1.iloc[0:4,-1]
y

42    148001.11
29    107138.38
6     127716.82
19         0.00
Name: Marketing Spend, dtype: float64

In [536]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95157.11427294])

In [537]:
df1.iloc[4,-1] = 95157.11

In [538]:

# Subtract 0th iteration from 1st iteration

df1 - df0

R&D Spend  Administration  Marketing Spend
42     0.0000            0.00             0.00
29  5193.7075            0.00             0.00
6      0.0000            0.00             0.00
19     0.0000       195942.41             0.00
28     0.0000            0.00        -22991.09

In [539]:

df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29        NaN       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       340708.94             0.00
28   66051.52       182645.56         95157.11

In [540]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-5619.41438824])

In [541]:

df2.iloc[1,0] = -5619.41

In [542]:

df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([329286.70744143])

In [543]:

df2.iloc[3,1] = 329286.70

In [544]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95654.79660719])

In [545]:
df2.iloc[4,-1] = 95654.79


In [546]:
df2

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29   -5619.41       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       329286.70             0.00
28   66051.52       182645.56         95654.79

In [547]:
df2-df1

R&D Spend  Administration  Marketing Spend
42       0.00            0.00             0.00
29  -88495.02            0.00             0.00
6        0.00            0.00             0.00
19       0.00       -11422.24             0.00
28       0.00            0.00           497.68

In [548]:

df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29        NaN       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       329286.70             0.00
28   66051.52       182645.56         95654.79

In [549]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([106.34799262])

In [550]:

df3.iloc[1,0] = 106.34

In [551]:

df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([329899.67886816])

In [552]:
df3.iloc[3,1] = 329899.67

In [553]:

df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

c:\Users\rohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95605.85842452])

In [554]:
df3.iloc[4,-1]=95605.85

In [555]:
df2.iloc[3,1] = 329286.70

In [556]:
df3

R&D Spend  Administration  Marketing Spend
42   23640.93        96189.63        148001.11
29     106.34       153032.06        107138.38
6   134615.46       147198.87        127716.82
19   86419.70       329899.67             0.00
28   66051.52       182645.56         95605.85

In [557]:
df3-df2

R&D Spend  Administration  Marketing Spend
42       0.00            0.00             0.00
29    5725.75            0.00             0.00
6        0.00            0.00             0.00
19       0.00          612.97             0.00
28       0.00            0.00           -48.94